/**
 * Verified tourist VAT / tax-free refund destinations.
 * Net refund % = typical amount returned to tourist after operator/admin fees
 * (Global Blue “Save up to X%”, or government scheme rules).
 *
 * Sources: globalblue.com/destinations, taxfree.weareplanet.com,
 * FTA UAE, IRAS SG, ATO TRS, Thailand RD, Egypt ETA, SARS ZA, DGT Indonesia,
 * Vietnam Decree 181/2025, French customs PABLO, Airvat/Solpay.
 */

export interface VatCountry {
  code: string;
  name: string;
  region: 'Europe' | 'Asia' | 'Middle East' | 'Americas' | 'Africa' | 'Oceania';
  refundType: 'Tax Free' | 'VAT Refund' | 'Detaxe' | 'GST Refund' | 'TRS';
  /** Statutory VAT / GST / consumption tax rate */
  vatRate: string;
  /** Typical net refund received by tourist (after fees) */
  refundRate: string;
  minSpend: string;
  /** Max time to export / validate after purchase */
  exportDeadline: string;
  /** Short label for cards */
  docs: string;
  /** Full document checklist */
  documentsRequired: string[];
  /** How customs / validation works at departure */
  customsValidation: string;
  /** Who qualifies */
  eligibility: string;
  score: number;
  tier: 'Elite' | 'Premium' | 'Standard';
  passportName: string;
  operators: string[];
}

export const VAT_COUNTRIES: VatCountry[] = [
  {
    code: 'AE',
    name: 'United Arab Emirates',
    region: 'Middle East',
    refundType: 'Tax Free',
    vatRate: '5%',
    refundRate: '~4.3% net',
    minSpend: 'AED 250 (excl. VAT) per purchase',
    exportDeadline: 'Validate within 90 days of purchase',
    docs: 'Passport, goods, departure ticket',
    documentsRequired: [
      'Original passport or GCC ID used to enter UAE',
      'Purchased goods (shown before luggage check-in)',
      'Valid departure ticket / boarding pass',
      'Tax invoice or digital tax-free tag from Planet store',
    ],
    customsValidation: 'Planet validation kiosk or desk at airport/seaport/border before check-in',
    eligibility: 'Non-resident visitor aged 18+; not cabin crew',
    score: 96,
    tier: 'Elite',
    passportName: 'UAE',
    operators: ['Planet (FTA)', 'Utu'],
  },
  {
    code: 'FR',
    name: 'France',
    region: 'Europe',
    refundType: 'Detaxe',
    vatRate: '20%',
    refundRate: 'Up to 20% net',
    minSpend: '€100.01 incl. VAT (same store/brand)',
    exportDeadline: 'Validate before end of 3rd month after purchase month',
    docs: 'Passport, detaxe form, PABLO scan',
    documentsRequired: [
      'Original passport (non-EU resident, age 16+)',
      'Tax-free export form with barcode (Bordereau de détaxe)',
      'Shop receipts / invoices',
      'Boarding pass or travel ticket',
      'Goods in luggage (must be available for inspection)',
    ],
    customsValidation: 'Scan form at PABLO kiosk at airport/station; green OK = customs validated',
    eligibility: 'Non-EU resident; goods for personal use; leaving EU from France',
    score: 95,
    tier: 'Elite',
    passportName: 'France',
    operators: ['Global Blue', 'Planet', 'Innova', 'Airvat', 'Solpay', 'Refundit'],
  },
  {
    code: 'IT',
    name: 'Italy',
    region: 'Europe',
    refundType: 'Tax Free',
    vatRate: '22%',
    refundRate: 'From 12% net',
    minSpend: '€70.01 incl. VAT (same day, same store)',
    exportDeadline: 'Validate at last EU departure within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: [
      'Original passport (non-EU resident)',
      'Tax-free form from participating retailer',
      'Original receipts',
      'Boarding pass',
      'Unused goods for customs inspection',
    ],
    customsValidation: 'Customs stamp or electronic validation (OTELLO/PABLO at major airports) at EU exit',
    eligibility: 'Non-EU resident; personal-use goods exported from EU',
    score: 94,
    tier: 'Elite',
    passportName: 'Italy',
    operators: ['Global Blue', 'Planet', 'Innova'],
  },
  {
    code: 'ES',
    name: 'Spain',
    region: 'Europe',
    refundType: 'Tax Free',
    vatRate: '21%',
    refundRate: 'Up to 17% net',
    minSpend: 'No minimum (since 2024)',
    exportDeadline: 'Validate at EU exit within 3 months of purchase',
    docs: 'Passport, tax-free form, DIVA/customs',
    documentsRequired: [
      'Original passport (non-EU resident)',
      'Tax-free form (Formulario de devolución)',
      'Purchase receipts',
      'Boarding pass',
      'Goods available for inspection',
    ],
    customsValidation: 'DIVA electronic terminal or customs desk at airport before departure',
    eligibility: 'Non-EU resident; goods exported from EU territory',
    score: 93,
    tier: 'Elite',
    passportName: 'Spain',
    operators: ['Global Blue', 'Planet', 'Innova'],
  },
  {
    code: 'DE',
    name: 'Germany',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '19%',
    refundRate: 'Up to 19% net',
    minSpend: '€50.01 incl. VAT (same store, same day)',
    exportDeadline: 'Customs stamp within 3 months; export from EU',
    docs: 'Passport, tax-free form, customs stamp',
    documentsRequired: [
      'Original passport (non-EU resident)',
      'Tax-free export form (Ausfuhrbescheinigung)',
      'Receipts showing VAT',
      'Boarding pass',
      'Goods unopened / available for inspection',
    ],
    customsValidation: 'German customs (Zoll) stamp at airport/border — last EU exit if leaving via another EU state',
    eligibility: 'Permanent residence outside EU; age 18+',
    score: 92,
    tier: 'Elite',
    passportName: 'Germany',
    operators: ['Global Blue', 'Planet', 'Innova'],
  },
  {
    code: 'JP',
    name: 'Japan',
    region: 'Asia',
    refundType: 'Tax Free',
    vatRate: '10% consumption tax',
    refundRate: 'Up to 10% net',
    minSpend: '¥5,500+ incl. tax (general goods; ¥1,100+ consumables)',
    exportDeadline: 'Export within 90 days (refund system from Nov 2026)',
    docs: 'Passport, receipt, customs terminal',
    documentsRequired: [
      'Passport (temporary visitor stamp / status)',
      'Tax-free purchase receipt from registered store',
      'Purchased goods (present at customs before baggage check-in)',
      'Boarding pass (at departure)',
    ],
    customsValidation: 'Tax-free procedure terminal at airport/seaport customs before luggage check-in',
    eligibility: 'Foreign tourist on short-term stay; not resident; goods exported from Japan',
    score: 91,
    tier: 'Elite',
    passportName: 'Japan',
    operators: ['Global Blue', 'Tourego', 'JAL DFS'],
  },
  {
    code: 'SG',
    name: 'Singapore',
    region: 'Asia',
    refundType: 'GST Refund',
    vatRate: '9% GST',
    refundRate: 'Up to 8% net',
    minSpend: 'S$100+ incl. GST (same retailer, up to 3 same-day receipts)',
    exportDeadline: 'Depart with goods within 2 months of purchase',
    docs: 'Passport, e-Visit Pass, eTRS receipt',
    documentsRequired: [
      'Original passport presented in store at purchase',
      'Electronic Visit Pass (e-Visit Pass) from ICA',
      'eTRS transaction linked to passport at participating retailer',
      'Boarding pass',
      'Goods for customs inspection if selected',
    ],
    customsValidation: 'eTRS self-help kiosk at Changi or Seletar Airport (before/after immigration per item type)',
    eligibility: 'Tourist departing by air from Changi or Seletar; not Singapore citizen/PR',
    score: 90,
    tier: 'Elite',
    passportName: 'Singapore',
    operators: ['Global Blue', 'eTRS (IRAS)', 'Utu'],
  },
  {
    code: 'CH',
    name: 'Switzerland',
    region: 'Europe',
    refundType: 'Tax Free',
    vatRate: '8.1% (standard)',
    refundRate: 'Up to 8.1% net',
    minSpend: 'CHF 300+ incl. VAT (same day, same store)',
    exportDeadline: 'Validate at Swiss border/airport within 30 days',
    docs: 'Passport, tax-free form, customs stamp',
    documentsRequired: [
      'Passport (non-Swiss resident)',
      'Tax-free form from retailer',
      'Receipts',
      'Goods unused and available for inspection',
    ],
    customsValidation: 'Swiss customs stamp at border/airport when leaving Switzerland (not EU — validate before leaving CH)',
    eligibility: 'Residence outside Switzerland; goods exported within 30 days',
    score: 89,
    tier: 'Premium',
    passportName: 'Switzerland',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'KR',
    name: 'South Korea',
    region: 'Asia',
    refundType: 'Tax Free',
    vatRate: '10% VAT',
    refundRate: 'Up to 10% net',
    minSpend: '₩15,000+ incl. VAT (same store, same day)',
    exportDeadline: 'Export within 3 months of purchase',
    docs: 'Passport, tax refund slip, customs',
    documentsRequired: [
      'Passport (foreign visitor)',
      'Tax refund receipt / form from store',
      'Goods (may be inspected at airport)',
      'Boarding pass',
    ],
    customsValidation: 'Korea Customs at airport — immediate refund at store or at departure desk/Kiosk',
    eligibility: 'Foreign tourist; goods taken out of Korea; not airline crew',
    score: 88,
    tier: 'Premium',
    passportName: 'South Korea',
    operators: ['Global Blue', 'Utu', 'KT Tourist Reward'],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '21%',
    refundRate: 'Up to 16% net',
    minSpend: '€50+ incl. VAT (same store, same day)',
    exportDeadline: 'Validate at EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: [
      'Original passport (non-EU resident)',
      'Tax-free form',
      'Receipts',
      'Boarding pass',
      'Goods for inspection',
    ],
    customsValidation: 'Digital or manual customs validation at Schiphol/other EU exit points',
    eligibility: 'Permanent residence outside EU',
    score: 87,
    tier: 'Premium',
    passportName: 'Netherlands',
    operators: ['Global Blue', 'Planet', 'Innova'],
  },
  {
    code: 'AT',
    name: 'Austria',
    region: 'Europe',
    refundType: 'Tax Free',
    vatRate: '20%',
    refundRate: 'Up to 20% net',
    minSpend: '€75.01 incl. VAT (same store, same day)',
    exportDeadline: 'EU exit validation within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: [
      'Passport (non-EU resident)',
      'Tax-free export document',
      'Receipts',
      'Goods unopened / for inspection',
    ],
    customsValidation: 'Customs stamp or electronic validation at Vienna/other EU departure',
    eligibility: 'Residence outside EU; personal-use goods',
    score: 86,
    tier: 'Premium',
    passportName: 'Austria',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'BE',
    name: 'Belgium',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '21%',
    refundRate: 'Up to 16% net',
    minSpend: '€125.01 incl. VAT (same store, same day)',
    exportDeadline: 'Customs validation within 3 months + current month',
    docs: 'Passport, tax-free form, EU customs',
    documentsRequired: [
      'Original passport (non-EU resident)',
      'Tax-free form',
      'Receipts',
      'Boarding pass',
      'Goods for inspection',
    ],
    customsValidation: 'Customs stamp at last EU departure (PABLO/DIVA if transiting via FR/ES)',
    eligibility: 'Residence outside EU; validate before leaving EU',
    score: 85,
    tier: 'Premium',
    passportName: 'Belgium',
    operators: ['Global Blue', 'Planet', 'Airvat', 'Solpay'],
  },
  {
    code: 'PT',
    name: 'Portugal',
    region: 'Europe',
    refundType: 'Tax Free',
    vatRate: '23%',
    refundRate: 'Up to 15% net',
    minSpend: '€61.50 incl. VAT (minimum per purchase)',
    exportDeadline: 'Validate at EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: [
      'Passport (non-EU resident)',
      'Tax-free form',
      'Receipts',
      'Boarding pass',
      'Goods for inspection',
    ],
    customsValidation: 'Customs validation at airport when leaving EU',
    eligibility: 'Non-EU resident exporting goods from EU',
    score: 84,
    tier: 'Premium',
    passportName: 'Portugal',
    operators: ['Global Blue', 'Planet', 'Innova'],
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    region: 'Middle East',
    refundType: 'VAT Refund',
    vatRate: '15% VAT',
    refundRate: 'Up to 11% net',
    minSpend: 'SAR 500+ incl. VAT',
    exportDeadline: 'Validate at departure from KSA',
    docs: 'Passport, tax invoice, customs',
    documentsRequired: [
      'Passport (eligible visitor visa)',
      'Tax invoices from participating stores',
      'Goods for inspection',
      'Boarding pass',
    ],
    customsValidation: 'Validation at airport via Global Blue / ZATCA process',
    eligibility: 'Eligible tourist/visitor; goods exported from Saudi Arabia',
    score: 83,
    tier: 'Premium',
    passportName: 'Saudi Arabia',
    operators: ['Global Blue'],
  },
  {
    code: 'TR',
    name: 'Türkiye',
    region: 'Middle East',
    refundType: 'Tax Free',
    vatRate: '10–20% VAT',
    refundRate: 'Up to 13.5% net',
    minSpend: 'TRY 1,000+ incl. VAT',
    exportDeadline: 'Validate when leaving Türkiye (not EU member)',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: [
      'Passport (non-resident)',
      'Tax-free form from retailer',
      'Receipts',
      'Goods for inspection at airport/border',
    ],
    customsValidation: 'Turkish customs stamp at airport — validate before leaving Turkey',
    eligibility: 'Residence outside Türkiye; export goods within 3 months',
    score: 82,
    tier: 'Premium',
    passportName: 'Turkey',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'TH',
    name: 'Thailand',
    region: 'Asia',
    refundType: 'VAT Refund',
    vatRate: '7% VAT',
    refundRate: 'Up to 6% net',
    minSpend: '฿2,000+/store/day; ฿5,000+ total for customs',
    exportDeadline: 'Export within 60 days of purchase',
    docs: 'Passport, P.P.10 form, receipts, goods',
    documentsRequired: [
      'Passport (foreign tourist, not crew)',
      'VAT Refund Application P.P.10 from store',
      'Tax invoices from “VAT REFUND FOR TOURISTS” stores',
      'Purchased goods (shown to customs before check-in if total ≥ ฿5,000)',
      'Boarding pass',
    ],
    customsValidation: 'Customs stamp on P.P.10 before check-in; refund counter after immigration',
    eligibility: 'Non-Thai passport holder; departing via international airport/seaport in Thailand',
    score: 81,
    tier: 'Premium',
    passportName: 'Thailand',
    operators: ['Thailand VRT (RD)', 'Global Blue'],
  },
  {
    code: 'AU',
    name: 'Australia',
    region: 'Oceania',
    refundType: 'TRS',
    vatRate: '10% GST',
    refundRate: 'Full 10% GST on goods',
    minSpend: 'A$300+ incl. GST (single retailer ABN, within 60 days)',
    exportDeadline: 'Claim at TRS facility ≥30 min before flight; goods within 60 days of purchase',
    docs: 'Passport, tax invoice, goods, boarding pass',
    documentsRequired: [
      'Passport',
      'Original tax invoice in English with retailer ABN',
      'Purchased goods (carry-on or checked — see ABF rules)',
      'International boarding pass',
      'Credit card for refund (optional)',
    ],
    customsValidation: 'Australian Border Force TRS desk at airport after security (goods inspection)',
    eligibility: 'Departing Australia internationally; goods only (not services/accommodation); GST was paid',
    score: 80,
    tier: 'Premium',
    passportName: 'Australia',
    operators: ['Tourist Refund Scheme (ABF)'],
  },
  {
    code: 'GR',
    name: 'Greece',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '24%',
    refundRate: 'Up to 19% net',
    minSpend: '€50+ incl. VAT (same store, same day)',
    exportDeadline: 'EU exit validation within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Boarding pass', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure point',
    eligibility: 'Non-EU resident',
    score: 79,
    tier: 'Standard',
    passportName: 'Greece',
    operators: ['Global Blue', 'Planet', 'Refundit'],
  },
  {
    code: 'IE',
    name: 'Ireland',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '23%',
    refundRate: 'Up to 18% net',
    minSpend: 'No minimum (Ireland)',
    exportDeadline: 'Validate at EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Boarding pass', 'Goods for inspection'],
    customsValidation: 'Customs stamp when leaving EU (Ireland is last EU exit if not transiting)',
    eligibility: 'Residence outside EU',
    score: 78,
    tier: 'Standard',
    passportName: 'Ireland',
    operators: ['Global Blue', 'Planet', 'Innova'],
  },
  {
    code: 'SE',
    name: 'Sweden',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '25%',
    refundRate: 'Up to 19% net',
    minSpend: 'SEK 200+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs validation at EU departure',
    eligibility: 'Permanent residence outside EU',
    score: 77,
    tier: 'Standard',
    passportName: 'Sweden',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'DK',
    name: 'Denmark',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '25%',
    refundRate: 'Up to 20% net',
    minSpend: 'DKK 300.01+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Boarding pass'],
    customsValidation: 'Customs at EU exit (Copenhagen airport if leaving EU from DK)',
    eligibility: 'Residence outside EU',
    score: 76,
    tier: 'Standard',
    passportName: 'Denmark',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'NO',
    name: 'Norway',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '25%',
    refundRate: 'Up to 19% net',
    minSpend: 'NOK 315+ incl. VAT',
    exportDeadline: 'Validate when leaving Norway (non-EU)',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Norwegian customs at border/airport — Norway is not EU',
    eligibility: 'Residence outside Norway; export within 3 months',
    score: 75,
    tier: 'Standard',
    passportName: 'Norway',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'FI',
    name: 'Finland',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '25.5% VAT',
    refundRate: 'Up to 18% net',
    minSpend: '€40+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident',
    score: 74,
    tier: 'Standard',
    passportName: 'Finland',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'PL',
    name: 'Poland',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '23%',
    refundRate: 'Up to 19% net',
    minSpend: 'PLN 200+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs validation at EU exit',
    eligibility: 'Residence outside EU',
    score: 73,
    tier: 'Standard',
    passportName: 'Poland',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '21%',
    refundRate: 'Up to 17% net',
    minSpend: 'CZK 2,001+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident',
    score: 72,
    tier: 'Standard',
    passportName: 'Czech Republic',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'HU',
    name: 'Hungary',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '27%',
    refundRate: 'Up to 19% net',
    minSpend: 'HUF 68,001+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Residence outside EU',
    score: 71,
    tier: 'Standard',
    passportName: 'Hungary',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'HR',
    name: 'Croatia',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '25%',
    refundRate: 'Up to 20% net',
    minSpend: '€100.01+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident since Croatia joined EU Schengen rules apply',
    score: 70,
    tier: 'Standard',
    passportName: 'Croatia',
    operators: ['Global Blue', 'Utu'],
  },
  {
    code: 'SK',
    name: 'Slovakia',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '23%',
    refundRate: 'Up to 20% net',
    minSpend: '€100+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Residence outside EU',
    score: 69,
    tier: 'Standard',
    passportName: 'Slovakia',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'CY',
    name: 'Cyprus',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '19%',
    refundRate: 'Up to 14% net',
    minSpend: '€50+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident',
    score: 68,
    tier: 'Standard',
    passportName: 'Cyprus',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '17%',
    refundRate: 'Up to 12.5% net',
    minSpend: '€74+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Residence outside EU',
    score: 67,
    tier: 'Standard',
    passportName: 'Luxembourg',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'MT',
    name: 'Malta',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '18%',
    refundRate: 'Up to 14% net',
    minSpend: 'Varies by retailer',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident',
    score: 66,
    tier: 'Standard',
    passportName: 'Malta',
    operators: ['Planet'],
  },
  {
    code: 'IS',
    name: 'Iceland',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '24%',
    refundRate: 'Up to 14% net',
    minSpend: 'ISK 12,000+ incl. VAT',
    exportDeadline: 'Validate when leaving Iceland (non-EU/EEA)',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at Keflavík airport when departing Iceland',
    eligibility: 'Residence outside Iceland; not EU member',
    score: 65,
    tier: 'Standard',
    passportName: 'Iceland',
    operators: ['Global Blue', 'Planet'],
  },
  {
    code: 'EE',
    name: 'Estonia',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '24%',
    refundRate: 'Up to 15% net',
    minSpend: '€38.01+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident',
    score: 64,
    tier: 'Standard',
    passportName: 'Estonia',
    operators: ['Global Blue'],
  },
  {
    code: 'LV',
    name: 'Latvia',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '21%',
    refundRate: 'Up to 15% net',
    minSpend: '€44+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Residence outside EU',
    score: 63,
    tier: 'Standard',
    passportName: 'Latvia',
    operators: ['Global Blue'],
  },
  {
    code: 'LT',
    name: 'Lithuania',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '21%',
    refundRate: 'Up to 14% net',
    minSpend: '€40+ incl. VAT',
    exportDeadline: 'EU exit within 3 months',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport (non-EU)', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at EU departure',
    eligibility: 'Non-EU resident',
    score: 62,
    tier: 'Standard',
    passportName: 'Lithuania',
    operators: ['Global Blue'],
  },
  {
    code: 'RS',
    name: 'Serbia',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '20%',
    refundRate: 'Up to 20% net',
    minSpend: 'RSD 6,000+ incl. VAT',
    exportDeadline: 'Validate when leaving Serbia',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at Serbian border/airport',
    eligibility: 'Foreign visitor; Serbia is not EU',
    score: 61,
    tier: 'Standard',
    passportName: 'Serbia',
    operators: ['Global Blue'],
  },
  {
    code: 'BH',
    name: 'Bahrain',
    region: 'Middle East',
    refundType: 'VAT Refund',
    vatRate: '10% VAT',
    refundRate: 'Up to 9% net',
    minSpend: 'Varies by retailer',
    exportDeadline: 'Validate at departure from Bahrain',
    docs: 'Passport, tax invoice, customs',
    documentsRequired: ['Passport', 'Tax invoices from participating stores', 'Goods for inspection'],
    customsValidation: 'Validation at airport via Planet',
    eligibility: 'Eligible visitor; goods exported from Bahrain',
    score: 60,
    tier: 'Standard',
    passportName: 'Bahrain',
    operators: ['Planet'],
  },
  {
    code: 'XI',
    name: 'Northern Ireland (UK)',
    region: 'Europe',
    refundType: 'VAT Refund',
    vatRate: '20% VAT',
    refundRate: 'Up to 16% net',
    minSpend: 'Varies (Retail Export Scheme)',
    exportDeadline: 'Validate when leaving NI for non-EU destination',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: [
      'Passport (non-EU visitor)',
      'Tax-free form under NI Retail Export Scheme',
      'Receipts',
      'Goods for inspection',
    ],
    customsValidation: 'HMRC customs validation when departing Northern Ireland',
    eligibility: 'Non-EU visitor only; Great Britain (England/Scotland/Wales) has no tourist VAT refund',
    score: 59,
    tier: 'Standard',
    passportName: 'United Kingdom',
    operators: ['Planet', 'Airvat'],
  },
  {
    code: 'ID',
    name: 'Indonesia',
    region: 'Asia',
    refundType: 'VAT Refund',
    vatRate: '11% VAT',
    refundRate: 'Up to 10% net',
    minSpend: 'Rp 500,000 total VAT (Rp 50k VAT per receipt min)',
    exportDeadline: 'Purchase within 30 days before departure; max 60-day stay',
    docs: 'Passport, tax invoice, boarding pass, goods',
    documentsRequired: [
      'Foreign passport (not Indonesian citizen/PR)',
      'Valid tax invoice from “Tax Free Shop” store',
      'Departure boarding pass',
      'Purchased goods as carry-on baggage',
    ],
    customsValidation: 'VAT refund counter (UPRPPN) at airport — officer verifies goods vs invoice',
    eligibility: 'Foreign passport holder; stay ≤60 days; one claim per visit',
    score: 57,
    tier: 'Standard',
    passportName: 'Indonesia',
    operators: ['DGT Tax Refund', 'Global Blue'],
  },
  {
    code: 'VN',
    name: 'Vietnam',
    region: 'Asia',
    refundType: 'VAT Refund',
    vatRate: '10% VAT',
    refundRate: '85% of VAT paid (~8.5%)',
    minSpend: '₫2,000,000+/store/day',
    exportDeadline: 'Invoice within 60 days of departure',
    docs: 'Passport, refund form, invoice, goods',
    documentsRequired: [
      'Original passport',
      'VAT refund declaration form from store',
      'Tax invoice with customs “Checked” stamp',
      'Boarding pass',
      'Unused goods matching invoice',
    ],
    customsValidation: 'Customs inspection & stamp before check-in; refund at bank counter after immigration',
    eligibility: 'Foreign tourist; not Vietnamese crew; goods exported via approved border gates',
    score: 56,
    tier: 'Standard',
    passportName: 'Vietnam',
    operators: ['Government VRT'],
  },
  {
    code: 'CN',
    name: 'China',
    region: 'Asia',
    refundType: 'VAT Refund',
    vatRate: '13% VAT (goods)',
    refundRate: 'Up to 13% net',
    minSpend: 'RMB 500+ incl. VAT (in pilot cities)',
    exportDeadline: 'Depart within 90 days of purchase (city rules vary)',
    docs: 'Passport, tax refund form, goods',
    documentsRequired: [
      'Passport (foreign visitor)',
      'VAT refund form from designated store',
      'Receipts',
      'Goods unopened for inspection at departure',
    ],
    customsValidation: 'Customs verification at international departure in eligible cities',
    eligibility: 'Foreign visitor in participating cities/stores; outbound within 90 days',
    score: 55,
    tier: 'Standard',
    passportName: 'China',
    operators: ['Global Blue'],
  },
  {
    code: 'EG',
    name: 'Egypt',
    region: 'Africa',
    refundType: 'VAT Refund',
    vatRate: '14% VAT',
    refundRate: 'Up to 12% net',
    minSpend: 'EGP 1,500+ per invoice',
    exportDeadline: 'Stay ≤3 months; goods exported on departure',
    docs: 'Passport, e-receipt, bank card, goods',
    documentsRequired: [
      'Passport (stay ≤3 months)',
      'E-receipt with passport number from “VAT Refund” store',
      'Goods in purchase condition',
      'Valid bank card for transfer',
    ],
    customsValidation: 'VAT refund office at airport — officer reviews goods & e-receipt',
    eligibility: 'Non-resident foreign visitor; goods accompany you abroad',
    score: 54,
    tier: 'Standard',
    passportName: 'Egypt',
    operators: ['Egypt ETA Tax Refund'],
  },
  {
    code: 'MA',
    name: 'Morocco',
    region: 'Africa',
    refundType: 'VAT Refund',
    vatRate: '20% VAT',
    refundRate: 'Up to 20% net',
    minSpend: 'MAD 2,000+ incl. VAT',
    exportDeadline: 'Validate when leaving Morocco',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at airport when departing Morocco',
    eligibility: 'Foreign tourist; goods exported from Morocco',
    score: 53,
    tier: 'Standard',
    passportName: 'Morocco',
    operators: ['Global Blue'],
  },
  {
    code: 'ZA',
    name: 'South Africa',
    region: 'Africa',
    refundType: 'VAT Refund',
    vatRate: '15% VAT',
    refundRate: 'Up to 14% net',
    minSpend: 'R250+ VAT-inclusive goods total',
    exportDeadline: 'Export within 90 days of invoice date',
    docs: 'Passport, tax invoice, goods, export proof',
    documentsRequired: [
      'Passport (tourist / non-resident)',
      'Original tax invoice from VAT-registered vendor',
      'Purchased goods for inspection',
      'Proof of export via designated commercial port',
    ],
    customsValidation: 'SARS customs or VAT Refund Administrator (VRA) at departure port',
    eligibility: 'Qualifying purchaser (tourist); movable goods exported within 90 days',
    score: 52,
    tier: 'Standard',
    passportName: 'South Africa',
    operators: ['VAT Refund Administrator (VRA)'],
  },
  {
    code: 'LB',
    name: 'Lebanon',
    region: 'Middle East',
    refundType: 'VAT Refund',
    vatRate: '11% VAT',
    refundRate: 'Up to 11% net',
    minSpend: 'USD 100+ incl. VAT',
    exportDeadline: 'Validate at departure from Lebanon',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at airport on departure',
    eligibility: 'Foreign visitor; goods exported from Lebanon',
    score: 51,
    tier: 'Standard',
    passportName: 'Lebanon',
    operators: ['Global Blue'],
  },
  {
    code: 'AR',
    name: 'Argentina',
    region: 'Americas',
    refundType: 'VAT Refund',
    vatRate: '21% VAT',
    refundRate: 'Up to 14% net',
    minSpend: 'ARS 70+ incl. VAT',
    exportDeadline: 'Validate when leaving Argentina',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'AFIP/customs validation at international departure',
    eligibility: 'Foreign tourist; goods exported from Argentina',
    score: 50,
    tier: 'Standard',
    passportName: 'Argentina',
    operators: ['Global Blue', 'Utu'],
  },
  {
    code: 'BS',
    name: 'Bahamas',
    region: 'Americas',
    refundType: 'Tax Free',
    vatRate: '12% VAT',
    refundRate: 'Up to 10% net',
    minSpend: 'BSD 25+ incl. VAT',
    exportDeadline: 'Validate at departure from Bahamas',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at airport when departing',
    eligibility: 'Foreign visitor exporting goods',
    score: 49,
    tier: 'Standard',
    passportName: 'Bahamas',
    operators: ['Global Blue'],
  },
  {
    code: 'CO',
    name: 'Colombia',
    region: 'Americas',
    refundType: 'VAT Refund',
    vatRate: '19% VAT',
    refundRate: 'Up to 12% net',
    minSpend: 'COP 157,122+ incl. VAT',
    exportDeadline: 'Validate at international departure',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'DIAN customs at airport',
    eligibility: 'Foreign tourist; goods exported from Colombia',
    score: 48,
    tier: 'Standard',
    passportName: 'Colombia',
    operators: ['Global Blue'],
  },
  {
    code: 'PE',
    name: 'Peru',
    region: 'Americas',
    refundType: 'VAT Refund',
    vatRate: '18% VAT',
    refundRate: 'Up to 11.5% net',
    minSpend: 'PEN 100+ incl. VAT',
    exportDeadline: 'Validate at departure from Peru',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'SUNAT/customs at international airport',
    eligibility: 'Foreign visitor exporting goods',
    score: 47,
    tier: 'Standard',
    passportName: 'Peru',
    operators: ['Global Blue'],
  },
  {
    code: 'UY',
    name: 'Uruguay',
    region: 'Americas',
    refundType: 'VAT Refund',
    vatRate: '22% VAT',
    refundRate: 'Up to 20% net',
    minSpend: 'UYU 600+ incl. VAT',
    exportDeadline: 'Validate when leaving Uruguay',
    docs: 'Passport, tax-free form, customs',
    documentsRequired: ['Passport', 'Tax-free form', 'Receipts', 'Goods for inspection'],
    customsValidation: 'Customs at international departure',
    eligibility: 'Foreign tourist; goods exported from Uruguay',
    score: 46,
    tier: 'Standard',
    passportName: 'Uruguay',
    operators: ['Global Blue'],
  },
];

export const ATLYS_MEDIA_CODES = new Set([
  'AE', 'FR', 'IT', 'ES', 'DE', 'JP', 'SG', 'CH', 'KR', 'NL', 'AT', 'BE', 'PT',
  'TR', 'TH', 'AU', 'GR', 'IE', 'SE', 'ID', 'VN', 'EG', 'ZA', 'CN', 'AR',
  'NO', 'FI', 'PL', 'CZ', 'HU', 'HR', 'DK', 'SA', 'MA', 'CO', 'PE', 'UY',
  'SK', 'CY', 'LU', 'MT', 'IS', 'EE', 'LV', 'LT', 'RS', 'BH', 'LB', 'BS',
]);

/** Regional proxy when Atlys has no asset (only XI → GB). */
const MEDIA_PROXY: Record<string, string> = {
  XI: 'GB',
};

export function countryMediaCode(code: string): string {
  if (MEDIA_PROXY[code]) return MEDIA_PROXY[code];
  if (ATLYS_MEDIA_CODES.has(code)) return code;
  return 'FR';
}

/** Parse statutory VAT/GST % from vatRate (e.g. "20%" or "10–20% VAT" → 20). */
export function parseVatRatePercent(vatRate: string): number {
  const range = vatRate.match(/(\d+(?:\.\d+)?)\s*[–-]\s*(\d+(?:\.\d+)?)\s*%/);
  if (range) return Math.max(parseFloat(range[1]), parseFloat(range[2]));
  const match = vatRate.match(/(\d+(?:\.\d+)?)\s*%/);
  return match ? parseFloat(match[1]) : 0;
}

export function getCountryByCode(code: string): VatCountry | undefined {
  return VAT_COUNTRIES.find((c) => c.code === code);
}

/** @deprecated Import from `./vatClaimMath` — re-exported via atlysAssets */
export { calculateClaimAmounts } from './vatClaimMath';

/** Parse leading numeric % from refundRate for sorting (e.g. "Up to 20% net" → 20). */
export function parseRefundRatePercent(rate: string): number {
  const paren = rate.match(/\(~?(\d+(?:\.\d+)?)\s*%\)/);
  if (paren) return parseFloat(paren[1]);
  const upTo = rate.match(/(?:up to|from)\s*~?(\d+(?:\.\d+)?)\s*%/i);
  if (upTo) return parseFloat(upTo[1]);
  const match = rate.match(/~?(\d+(?:\.\d+)?)\s*%/);
  return match ? parseFloat(match[1]) : 0;
}

/** Compact label for cards (e.g. "Up to 20% net" → "20%"). */
export function netRefundShort(rate: string): string {
  const pct = parseRefundRatePercent(rate);
  if (pct > 0) return `${pct}%`;
  return rate.replace(/^(Up to |From |~)/, '').replace(/ net$/, '').trim();
}
